import Settings from './src/settings';

export default ({
  gitlab: {
    url: 'https://lab.heliefb.com',
    token: '__GITLAB_TOKEN__',
    projectId: __GITLAB_PROJECT_ID__,
  },
  github: {
    // baseUrl: 'https://gitlab.mycompany.com:123/etc',
    owner: '__GITHUB_OWNER__',
    token: '__GITHUB_TOKEN__',
    repo: '__GITHUB_REPO__',
  },
  s3: {
    accessKeyId: '__AWS_ACCESS_KEY__',
    secretAccessKey: '__AWS__SECRET_ACCESS_KEY__',
    bucket: 'gitlab-issue-attachments',
  },
  usermap: {
    'r.spirka': 'riks',
    'g.schulz': 'tantchen',
    'm.siebert': 'markus135',
  },
  projectmap: {
    'admin-panel/admin-backend': 'HeliEFB/admin-panel-admin-backend',
    'admin-panel/ext-library': 'HeliEFB/admin-panel-ext-library',
    'admin-panel/heliefb-api': 'HeliEFB/admin-panel-heliefb-api',
    'admin-panel/heliefb-web': 'HeliEFB/admin-panel-heliefb-web',
    'backend/ext-library': 'HeliEFB/backend-ext-library',
    'backend/heliefb': 'HeliEFB/backend-heliefb',
    'backend/heliefb-api': 'HeliEFB/backend-heliefb-api',
    'backend/heliefb-web': 'HeliEFB/backend-heliefb-web',
    'backend/ios-sns-receive-test': 'HeliEFB/backend-ios-sns-receive-test',
    'backend/js-lib-documents-obstacles':
      'HeliEFB/backend-js-lib-documents-obstacles',
    'backend/location-db': 'HeliEFB/locations-location-db',
    'backend/node-heliefb-api-client':
      'HeliEFB/backend-node-heliefb-api-client',
    'backend/node-sns-push-test': 'HeliEFB/backend-node-sns-push-test',
    'backend/php-app-data-aggregation':
      'HeliEFB/backend-php-app-data-aggregation',
    'backend/php-app-documents': 'HeliEFB/backend-php-app-documents',
    'backend/php-app-notam-importer': 'HeliEFB/backend-php-app-notam-importer',
    'backend/php-app-reporting-api': 'HeliEFB/backend-php-app-reporting-api',
    'backend/php-libs/airport-metadata': 'HeliEFB/php-libs-airport-metadata',
    'backend/php-libs/config': 'HeliEFB/php-libs-config',
    'backend/php-libs/data': 'HeliEFB/php-libs-data',
    'backend/php-libs/dictionary': 'HeliEFB/php-libs-dictionary',
    'backend/php-libs/documents-datasource-faa-dcs':
      'HeliEFB/php-libs-document-datasource-faa-dcs',
    'backend/php-libs/documents-datasource-faa-ddof':
      'HeliEFB/php-libs-document-datasource-faa-ddof',
    'backend/php-libs/documents-datasource-faa-dof':
      'HeliEFB/php-libs-document-datasource-faa-dof',
    'backend/php-libs/documents-datasource-faa-dtpp':
      'HeliEFB/php-libs-documents-datasource-faa-dtpp',
    'backend/php-libs/documents-datasource-faa-ocn':
      'HeliEFB/php-libs-documents-datasource-faa-ocn',
    'backend/php-libs/documents-datasource-nfdc-nasr':
      'HeliEFB/php-libs-documents-datasource-nfdc-nasr',
    'backend/php-libs/efb': 'HeliEFB/php-libs-efb',
    'backend/php-libs/importer-base': 'HeliEFB/php-libs-importer-base',
    'backend/php-libs/notam-base': 'HeliEFB/php-libs-notam-base',
    'backend/php-libs/notam-datasource-dfs':
      'HeliEFB/php-libs-notam-datasource-dfs',
    'backend/php-libs/notam-importer': 'HeliEFB/php-libs-notam-importer',
    'backend/php-libs/sns-messages': 'HeliEFB/php-libs-sns-messages',
    'backend/php-libs/weather-base': 'HeliEFB/php-libs-weather-base',
    'backend/php-libs/weather-datasource-dtn':
      'HeliEFB/php-libs-weather-datasource-dtn',
    'backend/php-libs/weather-datasource-dwd':
      'HeliEFB/php-libs-weather-datasource-dwd',
    'backend/php-libs/weather-datasource-noaa':
      'HeliEFB/php-libs-weather-datasource-noaa',
    'backend/php-libs/weather-importer': 'HeliEFB/php-libs-weather-importer',
    'backend/php-libs/weather-messagetype-dtn':
      'HeliEFB/php-libs-weather-messagetype-dtn',
    'backend/php-libs/weather-messagetype-metar':
      'HeliEFB/php-libs-weather-messagetype-metar',
    'backend/php-libs/weather-messagetype-sigmet':
      'HeliEFB/php-libs-weather-messagetype-sigmet',
    'backend/php-libs/weather-messagetype-taf':
      'HeliEFB/php-libs-weather-messagetype-taf',
    'backend/php-libs/weather-storage': 'HeliEFB/php-libs-weather-storage',
    'backend/php-libs/weather-storage-s3':
      'HeliEFB/php-libs-weather-storage-s3',
    'backend/php-libs/weather-visibilitycodes':
      'HeliEFB/php-libs-weather-visibilitycodes',
    'backend/php-package-catalog': 'HeliEFB/backend-php-package-catalog',
    'backend/php-weather-importer': 'HeliEFB/backend-php-weather-importer',
    'backend/reporting': 'HeliEFB/backend-reporting',
    'backend/tank-fill-macro': 'HeliEFB/tank-fill-macro',
    'backend/weather': 'HeliEFB/backend-weather',
    'backend/weather-server': 'HeliEFB/backend-weather-server',
    'backend/weather-service': 'HeliEFB/backend-weather-service',
    'customer/adac/airports-cleanup': 'HeliEFB/locations-airports-cleanup',
    'customer/adac/efb-geodata-update': 'HeliEFB/locations-geodata-update',
    'customer/adac/fuel-stations': 'HeliEFB/locations-fuel-stations',
    'customer/adac/location-importer': 'HeliEFB/locations-importer',
    'customer/adac/media-zipper': 'HeliEFB/ops-media-zipper',
    'customer/adac/openaip-airports-converter':
      'HeliEFB/locations-openaip-airports-converter',
    'customer/amc/users-csv-export': 'HeliEFB/ops-users-csv-export',
    'customer/expo/caltrans-heliplates': 'HeliEFB/expo-caltrans-heliplates',
    'customer/expo/expo-vm': 'HeliEFB/expo-vm',
    'doc/api': 'HeliEFB/doc-api',
    'doc/risk-assessment': 'HeliEFB/doc-risk-assessment',
    'doc/user-guide': 'HeliEFB/doc-user-guide',
    'ios/app': 'HeliEFB/ios-app',
    'ios/certificates': 'HeliEFB/ios-certificates',
    'ios/cordova-plugin-helipdfkit': 'HeliEFB/ios-cordova-plugin-helipdfkit',
    'ios/core-data-helpers': 'HeliEFB/ios-core-data-helpers',
    'ios/core-data-store': 'HeliEFB/ios-core-data-store',
    'ios/crypto': 'HeliEFB/ios-crypto',
    'ios/EFB': 'HeliEFB/ios-efb',
    'ios/efb-cordova-app': 'HeliEFB/ios-efb-cordova-app',
    'ios/EFBAPIClient': 'HeliEFB/ios-efb-api-client',
    'ios/EFBConfiguration': 'HeliEFB/ios-efb-configuration',
    'ios/EFBForms': 'HeliEFB/ios-efb-forms',
    'ios/EFBGraph': 'HeliEFB/ios-efb-graph',
    'ios/EFBUnitConverter': 'HeliEFB/ios-efb-unit-converter',
    'ios/EFBWeatherService': 'HeliEFB/ios-efb-weather-service',
    'ios/flightlog': 'HeliEFB/ios-flightlog',
    'ios/frat': 'HeliEFB/ios-frat',
    'ios/frat-cordova-app': 'HeliEFB/ios-frat-cordova-app',
    'ios/helipdfkit': 'HeliEFB/ios-helipdfkit',
    'ios/ios-deploy': 'HeliEFB/ios-deploy',
    'ios/ios-sns-receive-test': 'HeliEFB/ios-sns-receive-test',
    'ios/layoutable': 'HeliEFB/ios-layoutable',
    'ios/models': 'HeliEFB/ios-models',
    'ios/pod-template': 'HeliEFB/ios-pod-template',
    'ios/pods': 'HeliEFB/ios-pods',
    'ios/preflight-cordova-app': 'HeliEFB/ios-preflight-cordova-app',
    'ios/proj': 'HeliEFB/proj',
    'ios/safe': 'HeliEFB/ios-safe',
    'ios/scrollable-stack-view-controller':
      'HeliEFB/ios-scrollable-stack-view-controller',
    'ios/segmented-control': 'HeliEFB/ios-segmented-control',
    'ios/segmented-view-controller': 'HeliEFB/ios-segmented-view-controller',
    'ios/store': 'HeliEFB/ios-store',
    'ios/swift-weather-lib': 'HeliEFB/ios-swift-weather-lib',
    'ios/units': 'HeliEFB/ios-units',
    'ios/views': 'HeliEFB/ios-views',
    'ios/weather-client-sdk': 'HeliEFB/ios-weather-client-sdk',
    'maps/geojson-reduce': 'HeliEFB/maps-geojson-reduce',
    'maps/mapFAA': 'HeliEFB/maps-mapFAA',
    'maps/maps': 'HeliEFB/maps-maps',
    'maps/maps_cut': 'HeliEFB/maps-maps-cut',
    'maps/maps_ecs': 'HeliEFB/maps-maps-ecs',
    'maps/maps_rgb': 'HeliEFB/maps-maps-rgb',
    'maps/maps_with_tilemill': 'HeliEFB/maps-faa-maps-with-tilemill',
    'maps/openflightmap-generator': 'HeliEFB/maps-openflightmap-generator',
    'ops/administration': 'HeliEFB/administration',
    'ops/alpine-bash': 'HeliEFB/ops-alpine-bash',
    'ops/alpine-bash-make': 'HeliEFB/ops-alpine-bash-make',
    'ops/checkout-form-generator': 'HeliEFB/checkout-form-generator',
    'ops/csr-generator': 'HeliEFB/ops-csr-generator',
    'ops/homepage': 'HeliEFB/homepage',
    'ops/incident-response-plans': 'HeliEFB/ops-incident-response-plans',
    'ops/schneider-weather-proxy': 'HeliEFB/weather-schneider-weather-proxy',
    'ops/server-backup': 'HeliEFB/ops-server-backup',
    'ops/uploads': 'HeliEFB/ops-uploads',
    'r.spirka/app': 'riks/app',
    'r.spirka/archive': 'riks/archive',
    'r.spirka/cordova-plugin-helinotifications':
      'riks/cordova-plugin-helinotifications',
    'r.spirka/dev-stack': 'riks/dev-stack',
    'r.spirka/elevation-service': 'riks/elevation-service',
    'r.spirka/heliefb-api-demo': 'riks/heliefb-api-demo',
    'r.spirka/heliefb-vm': 'riks/heliefb-vm',
    'r.spirka/jira2gitlab': 'riks/jira2gitlab',
    'r.spirka/obstacles': 'riks/obstacles',
    'r.spirka/osm2geodb': 'riks/osm2geodb',
    'r.spirka/pushnotificationtest-cordova':
      'riks/pushnotificationtest-cordova',
    'r.spirka/users-update': 'riks/users-update',
    'r.spirka/webviewtest': 'riks/webviewtest',
  },
  conversion: {
    useLowerCaseLabels: true,
  },
  transfer: {
    milestones: false,
    labels: true,
    issues: true,
    mergeRequests: false,
  },
  debug: false,
  usePlaceholderIssuesForMissingIssues: true,
  useReplacementIssuesForCreationFails: true,
  useIssuesForAllMergeRequests: false,
  filterByLabel: null,
  skipMatchingComments: [],
  mergeRequests: {
    logFile: './merge-requests.json',
    log: false,
  },
} as unknown) as Settings;
